# Generated by Django 6.0.4 on 2026-04-20 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop', models.CharField(max_length=255, unique=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('isonline', models.BooleanField(default=False)),
                ('scope', models.TextField(blank=True, null=True)),
                ('expires', models.DateTimeField(blank=True, null=True)),
                ('access_token', models.CharField(blank=True, max_length=255, null=True)),
                ('refresh_token', models.CharField(blank=True, max_length=255, null=True)),
                ('refresh_token_expires', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
