# Generated by Django 6.0.4 on 2026-04-19 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('shop', models.TextField()),
                ('state', models.TextField()),
                ('isonline', models.BooleanField(db_column='isOnline')),
                ('scope', models.TextField(blank=True, null=True)),
                ('expires', models.DateTimeField(blank=True, null=True)),
                ('accesstoken', models.TextField(db_column='accessToken')),
                ('userid', models.BigIntegerField(blank=True, db_column='userId', null=True)),
                ('firstname', models.TextField(blank=True, db_column='firstName', null=True)),
                ('lastname', models.TextField(blank=True, db_column='lastName', null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('accountowner', models.BooleanField(db_column='accountOwner')),
                ('locale', models.TextField(blank=True, null=True)),
                ('collaborator', models.BooleanField(blank=True, null=True)),
                ('emailverified', models.BooleanField(blank=True, db_column='emailVerified', null=True)),
                ('refreshtoken', models.TextField(blank=True, db_column='refreshToken', null=True)),
                ('refreshtokenexpires', models.DateTimeField(blank=True, db_column='refreshTokenExpires', null=True)),
            ],
            options={
                'db_table': 'Session',
                'managed': False,
            },
        ),
    ]
